In [ ]:
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.1.3
Pandas version: 2.2.3

In [ ]:
df = pd.read_csv("Iris.csv")
print("Successful upload")

Successful upload

In [ ]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Number of Rows and Columns in form of tuple

In [ ]:
df.shape

(150, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

Statistical Operation

In [ ]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

Print columns

In [ ]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
print(df.dtypes)

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

calculate mean of numerical colums:

In [ ]:
print("Mean:")
print(df.mean(numeric_only=True))

Mean:
Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

calculate minimum

In [ ]:
df.min(numeric_only=True)

Id               1.0
SepalLengthCm    4.3
SepalWidthCm     2.0
PetalLengthCm    1.0
PetalWidthCm     0.1
dtype: float64

In [ ]:
df.max(numeric_only=True)

Id               150.0
SepalLengthCm      7.9
SepalWidthCm       4.4
PetalLengthCm      6.9
PetalWidthCm       2.5
dtype: float64

selecting a column

In [ ]:
df['Id']

0        1
1        2
2        3
3        4
4        5
      ...
145    146
146    147
147    148
148    149
149    150
Name: Id, Length: 150, dtype: int64

select many columns

In [ ]:
df[['Id', 'SepalLengthCm', 'SepalWidthCm']]

      Id  SepalLengthCm  SepalWidthCm
0      1            5.1           3.5
1      2            4.9           3.0
2      3            4.7           3.2
3      4            4.6           3.1
4      5            5.0           3.6
..   ...            ...           ...
145  146            6.7           3.0
146  147            6.3           2.5
147  148            6.5           3.0
148  149            6.2           3.4
149  150            5.9           3.0

[150 rows x 3 columns]

selecting rows

In [ ]:
print(df.iloc[0:5])

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

only 0th index no

In [ ]:
print(df.iloc[0])

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

row 10 to 15

display flowers having petal length greater than 5

In [ ]:
result = df[df["PetalLengthCm"]>5]
print(result)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
83    84            6.0           2.7            5.1           1.6
100  101            6.3           3.3            6.0           2.5
101  102            5.8           2.7            5.1           1.9
102  103            7.1           3.0            5.9           2.1
103  104            6.3           2.9            5.6           1.8
104  105            6.5           3.0            5.8           2.2
105  106            7.6           3.0            6.6           2.1
107  108            7.3           2.9            6.3           1.8
108  109            6.7           2.5            5.8           1.8
109  110            7.2           3.6            6.1           2.5
110  111            6.5           3.2            5.1           2.0
111  112            6.4           2.7            5.3           1.9
112  113            6.8           3.0            5.5           2.1
114  115            5.8           2.8            5.1           2.4
115  116            6.4           3.2            5.3           2.3
116  117            6.5           3.0            5.5           1.8
117  118            7.7           3.8            6.7           2.2
118  119            7.7           2.6            6.9           2.3
120  121            6.9           3.2            5.7           2.3
122  123            7.7           2.8            6.7           2.0
124  125            6.7           3.3            5.7           2.1
125  126            7.2           3.2            6.0           1.8
128  129            6.4           2.8            5.6           2.1
129  130            7.2           3.0            5.8           1.6
130  131            7.4           2.8            6.1           1.9
131  132            7.9           3.8            6.4           2.0
132  133            6.4           2.8            5.6           2.2
133  134            6.3           2.8            5.1           1.5
134  135            6.1           2.6            5.6           1.4
135  136            7.7           3.0            6.1           2.3
136  137            6.3           3.4            5.6           2.4
137  138            6.4           3.1            5.5           1.8
139  140            6.9           3.1            5.4           2.1
140  141            6.7           3.1            5.6           2.4
141  142            6.9           3.1            5.1           2.3
142  143            5.8           2.7            5.1           1.9
143  144            6.8           3.2            5.9           2.3
144  145            6.7           3.3            5.7           2.5
145  146            6.7           3.0            5.2           2.3
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

             Species
83   Iris-versicolor
100   Iris-virginica
101   Iris-virginica
102   Iris-virginica
103   Iris-virginica
104   Iris-virginica
105   Iris-virginica
107   Iris-virginica
108   Iris-virginica
109   Iris-virginica
110   Iris-virginica
111   Iris-virginica
112   Iris-virginica
114   Iris-virginica
115   Iris-virginica
116   Iris-virginica
117   Iris-virginica
118   Iris-virginica
120   Iris-virginica
122   Iris-virginica
124   Iris-virginica
125   Iris-virginica
128   Iris-virginica
129   Iris-virginica
130   Iris-virginica
131   Iris-virginica
132   Iris-virginica
133   Iris-virginica
134   Iris-virginica
135   Iris-virginica
136   Iris-virginica
137   Iris-virginica
139   Iris-virginica
140   Iris-virginica
141   Iris-virginica
142   Iris-virginica
143   Iris-virginica
144   Iris-virginica
145   Iris-virginica
147   Iris-virginica
148   Iris-virginica
149   Iris-virginica

Multiple conditions using &

In [ ]:
result = df[
    (df["PetalLengthCm"] > 5) &
    (df["PetalWidthCm"] > 2)
]
print(result)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
100  101            6.3           3.3            6.0           2.5
102  103            7.1           3.0            5.9           2.1
104  105            6.5           3.0            5.8           2.2
105  106            7.6           3.0            6.6           2.1
109  110            7.2           3.6            6.1           2.5
112  113            6.8           3.0            5.5           2.1
114  115            5.8           2.8            5.1           2.4
115  116            6.4           3.2            5.3           2.3
117  118            7.7           3.8            6.7           2.2
118  119            7.7           2.6            6.9           2.3
120  121            6.9           3.2            5.7           2.3
124  125            6.7           3.3            5.7           2.1
128  129            6.4           2.8            5.6           2.1
132  133            6.4           2.8            5.6           2.2
135  136            7.7           3.0            6.1           2.3
136  137            6.3           3.4            5.6           2.4
139  140            6.9           3.1            5.4           2.1
140  141            6.7           3.1            5.6           2.4
141  142            6.9           3.1            5.1           2.3
143  144            6.8           3.2            5.9           2.3
144  145            6.7           3.3            5.7           2.5
145  146            6.7           3.0            5.2           2.3
148  149            6.2           3.4            5.4           2.3

            Species
100  Iris-virginica
102  Iris-virginica
104  Iris-virginica
105  Iris-virginica
109  Iris-virginica
112  Iris-virginica
114  Iris-virginica
115  Iris-virginica
117  Iris-virginica
118  Iris-virginica
120  Iris-virginica
124  Iris-virginica
128  Iris-virginica
132  Iris-virginica
135  Iris-virginica
136  Iris-virginica
139  Iris-virginica
140  Iris-virginica
141  Iris-virginica
143  Iris-virginica
144  Iris-virginica
145  Iris-virginica
148  Iris-virginica

sort from highest to lowest

In [ ]:
sorted_df = df.sort_values("PetalLengthCm")
print(sorted_df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
22    23            4.6           3.6            1.0           0.2
13    14            4.3           3.0            1.1           0.1
14    15            5.8           4.0            1.2           0.2
35    36            5.0           3.2            1.2           0.2
16    17            5.4           3.9            1.3           0.4
..   ...            ...           ...            ...           ...
131  132            7.9           3.8            6.4           2.0
105  106            7.6           3.0            6.6           2.1
117  118            7.7           3.8            6.7           2.2
122  123            7.7           2.8            6.7           2.0
118  119            7.7           2.6            6.9           2.3

            Species
22      Iris-setosa
13      Iris-setosa
14      Iris-setosa
35      Iris-setosa
16      Iris-setosa
..              ...
131  Iris-virginica
105  Iris-virginica
117  Iris-virginica
122  Iris-virginica
118  Iris-virginica

[150 rows x 6 columns]

counting dif spicies

In [ ]:
print(df["Species"].value_counts())

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

NumPy operation (petal name into numpy array)

In [ ]:
petal_length = np.array(df["PetalLengthCm"])
print("Petal length:")
print(petal_length)

Petal length:
[1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.5 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
 4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
 4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3
 5.8 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.
 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
 5.7 5.2 5.  5.2 5.4 5.1]

mean using numPy

In [ ]:
print("Mean petal length: ", np.mean(petal_length))

Mean petal length:  3.758666666666666

calculate stardard deviation

In [ ]:
print("Standard Deviation:",np.std(petal_length))

Standard Deviation: 1.7585291834055212